### ISSUE TITLE
工作流设计及培训

### ISSUE THREAD

**Issue by hycarbon-b** [hycarbon-b/GTI_FORMULA_STUDENT#2]
完善工作流的教学文档（readme）：
1. 注册Github
2. Name（不是账户名）改成完整的名字
3. 介绍project的各项功能，如何分配任务，分配任务需答复收到，完成后再次回复，只有分配者有权限将任务移动至Done
4. 介绍Onedrive的使用，workspace中各个文件夹存放哪些文件
5. department weekly meeting 
6. ppt、report的模板如何使用

**Comment by hycarbon-b** [comment]
以后收到assignment都回复一下

**Comment by shui85** [comment]
收到，正在打readme

**Comment by shui85** [comment]
![Image](https://github.com/hycarbon-b/GTI_FORMULA_STUDENT/assets/152281369/13065a41-e674-4f9f-8733-68a77dcba63b)

**Comment by shui85** [comment]
已完成

**Comment by husiansbhs** [comment]
zhaoxuan huang 黄昭轩
