### ISSUE TITLE
presentation的奖状

### ISSUE THREAD

**Issue by shui85** [hycarbon-b/GTI_FORMULA_STUDENT#4]

**Comment by shui85** [comment]
内容：奖状共分为两部分：内芯和外壳，各30份，总价129.99 + 125.98 + 256.99 = 512.96 人民币
其中255.97元为外壳成本加定制费，256.99为内芯成本加定制费

24/3/18进度：
内页到达，经检查后没有出现漏印等问题，暂时存放于周世伟处

**Comment by hycarbon-b** [comment]
订单记录的图片上传一下，留个档

**Comment by shui85** [comment]
![Image](https://github.com/hycarbon-b/GTI_FORMULA_STUDENT/assets/152281369/c45df3a5-67fd-4f2a-a0ce-e5279864980a)

**Comment by shui85** [comment]
@hycarbon-b 跟大家说一下开票开哪里的，现在是否能用广以的名字来开

**Comment by shui85** [comment]
我突然发现不知道开什么票，不知道能不能拿学校开，就没开票

**Comment by hycarbon-b** [comment]
之后都拿学校的户头开，虽然暂时不会有报销，但开着总比没有好
