### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by shui85** [hycarbon-b/GTI_FORMULA_STUDENT#5]
由 汪逸翔 与 xinyao 负责会议管理

**Comment by hycarbon-b** [comment]
由我制作Group Discussion引导文档，工作流培训的文档再更新一下，完善内容

**Comment by hycarbon-b** [comment]
@shui85 找个人到时候多拍一些照片，不用找官方媒体

**Comment by hycarbon-b** [comment]
group discussion 文档已完成，等待修改细节
https://github.com/hycarbon-b/GTI_FORMULA_STUDENT/blob/main/conference/3_23_warmup.md

**Comment by hycarbon-b** [comment]
1. 更新group a list
2. 完善引导文档
3. 各部门需要讨论的内容
4. ppt
